[package]
name = "maze_gen"
version = "0.1.0"
edition = "2018"

[lib]
name = "maze_gen"
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/main.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
